name: AutoHub ci

on:
  push:
    branches:
      - master

jobs:
  Build & Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.16

      - name: Install Node Dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build
        run: CI='' npm run build

      - name: Deploy to Firebase
        run: firebase deploy --token $FIREBASE_TOKEN
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
